name: authentication_repository
description: A new Flutter project.
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  cache:
    path: ../cache
  equatable: 2.0.5
  firebase_auth: 4.17.8
  firebase_core: 2.27.0
  flutter:
    sdk: flutter
  google_sign_in: 6.2.1
  meta: 1.10.0

dev_dependencies:
  flutter_lints: 3.0.1
